# Generated by Django 3.0.7 on 2020-07-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_message_msgtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='msgtype',
        ),
        migrations.AddField(
            model_name='message',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='lastactive',
            field=models.IntegerField(default=0),
        ),
    ]
